apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  namespace: vti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: huanvt2302/vti_demo:2.0
        volumeMounts:
          - name: hello-python-config
            mountPath: /path/config
        ports:
          - containerPort: 5001
      volumes:
        - name: hello-python-config
          configMap:
            name: hello-python-config
      restartPolicy: Always

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-python-config
  namespace: vti
data:
  env-dev.properties: |
    author=Huan
    difficulty=medium

---

apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: vti
spec:
  selector:
    app: hello-python
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

