apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vti
  name: configmap-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "watch", "list" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: vti
subjects:
  - kind: ServiceAccount
    name: default
    namespace: vti
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
